language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update

before_script:
  - pear install -f pear/PHP_CodeSniffer-1.5.6
  - git clone https://github.com/joomla/coding-standards.git `pear config-get php_dir`/PHP/CodeSniffer/Standards/Joomla
  - phpenv rehash

script:
  - composer test

