language: php
php:
  - 7.1
  - 7.2

before_install:
  - npm install -g bower
  - composer self-update
  - composer install

  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

script:
  - composer test
  - moodle-plugin-ci phplint

